/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'ai',
    path: '/ai',
    component: 'layout.base',
    meta: {
      title: 'ai',
      i18nKey: 'route.ai'
    },
    children: [
      {
        name: 'ai_chat',
        path: '/ai/chat',
        component: 'view.ai_chat',
        meta: {
          title: 'ai_chat',
          i18nKey: 'route.ai_chat'
        }
      },
      {
        name: 'ai_provider',
        path: '/ai/provider',
        component: 'view.ai_provider',
        meta: {
          title: 'ai_provider',
          i18nKey: 'route.ai_provider'
        }
      }
    ]
  },
  {
    name: 'app',
    path: '/app',
    component: 'layout.base$view.app',
    meta: {
      title: 'app',
      i18nKey: 'route.app'
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'marketplace',
    path: '/marketplace',
    component: 'layout.base$view.marketplace',
    meta: {
      title: 'marketplace',
      i18nKey: 'route.marketplace'
    }
  },
  {
    name: 'marketplace-detail',
    path: '/marketplace/detail',
    component: 'layout.base$view.marketplace-detail',
    meta: {
      title: 'marketplace-detail',
      i18nKey: 'route.marketplace-detail'
    }
  },
  {
    name: 'marketplace-installed',
    path: '/marketplace/installed',
    component: 'layout.base$view.marketplace-installed',
    meta: {
      title: 'marketplace-installed',
      i18nKey: 'route.marketplace-installed'
    }
  },
  {
    name: 'marketplace-review',
    path: '/marketplace-review',
    component: 'layout.base$view.marketplace-review',
    meta: {
      title: 'marketplace-review',
      i18nKey: 'route.marketplace-review'
    }
  },
  {
    name: 'marketplace-upload',
    path: '/marketplace/upload',
    component: 'layout.base$view.marketplace-upload',
    meta: {
      title: 'marketplace-upload',
      i18nKey: 'route.marketplace-upload'
    }
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base$view.profile',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        },
        children: [
          {
            name: 'system_dict_data',
            path: '/system/dict/data',
            component: 'view.system_dict_data',
            meta: {
              title: 'system_dict_data',
              i18nKey: 'route.system_dict_data'
            }
          }
        ]
      },
      {
        name: 'system_file',
        path: '/system/file',
        component: 'view.system_file',
        meta: {
          title: 'system_file',
          i18nKey: 'route.system_file'
        }
      },
      {
        name: 'system_job',
        path: '/system/job',
        component: 'view.system_job',
        meta: {
          title: 'system_job',
          i18nKey: 'route.system_job'
        }
      },
      {
        name: 'system_job-log',
        path: '/system/job-log',
        component: 'view.system_job-log',
        meta: {
          title: 'system_job-log',
          i18nKey: 'route.system_job-log'
        }
      },
      {
        name: 'system_login-log',
        path: '/system/login-log',
        component: 'view.system_login-log',
        meta: {
          title: 'system_login-log',
          i18nKey: 'route.system_login-log'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_operation-log',
        path: '/system/operation-log',
        component: 'view.system_operation-log',
        meta: {
          title: 'system_operation-log',
          i18nKey: 'route.system_operation-log'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  }
];
